name: "Acceptance - Collections"
description: "Validate Collections"
title: "Release [Version] Acceptance Testing: Collections"
labels:
  - acceptance-testing
  - collections
  - landing-page

body:
  - type: markdown
    attributes:
      value: >-
        Be sure to replace [Version] in the title above.  If necessary, update the testing
        platform, and provide any special instructions.  Assign to a developer for
        completion. 

  - type: textarea
    id: instructions
    attributes:
      label: Instructions
      value: >-
        Please test the release candidate running on the platform noted below and confirm
        the assertions listed below; check the box by each assertion when you have
        confirmed compliance.  If you encounter problems, describe them in comments to
        this issue (and @-tag relevent devlopers), and consider creating a sub-issue.
        When all assertions are confirmed and no problems remain open, click the "Testing
        Complete" box and close this issue. 


        Note checking multiple broswers or OS platforms is _not_ required, unless explicitly
        requested.


        See the [Acceptance Testing page on
        Confluence](https://nistgov.atlassian.net/wiki/spaces/OKB/pages/15959145/Acceptance+Testing)
        for more information.  

  - type: input
    id: platform
    attributes:
      label: Testing Platform
      value: testdata.nist.gov
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Collections"
        

  - type: checkboxes
    id: collection_checks
    attributes:
      label: Collections Checklist
      options:
        - label: Page features appropriate image and color scheme
        - label: Left-side filters include collection-specific research areas
        - label: Bar above dataset listing includes number of datasets, page selection, sort-by selection box, and free-text filtering
        - label: Each dataset entry includes title link and “Access Data” link; title link always goes to PDR landing page

  - type: markdown
    attributes:
      value: "## Collection Member Landing Page"

  - type: checkboxes
    id: member_checks
    attributes:
      label: Collection Member Checklist
      options:
        - label: “Part of the..” statement appears under title with working collection link
        - label: Collection-specific research topics are listed (next to NIST taxonomy terms).

  - type: checkboxes
    id: browser
    attributes:
      label: Browser(s) tested on (check all that apply; all not required)
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge
        - label: Other
          
  - type: checkboxes
    id: os
    attributes:
      label: OS platform(s) tested on (check all that apply; all not required)
      options:
        - label: Mac
        - label: Linux
        - label: Windows
        - label: Android
        - label: iOS (IPhone/IPad)
        - label: Other
          
  - type: checkboxes
    id: completion
    attributes:
      label: Testing Completed
      options:
        - label: all acceptance tests completed with no issues found


