name: "Acceptance - SDP and Search"
description: "Validate Science Data Portal (SDP) and Search Results on testdata.nist.gov"
title: "Release [Version] Acceptance Testing: SDP/Search"
labels:
  - acceptance-testing
  - sdp
  - search
body:
  - type: markdown
    attributes:
      value: >-
        Be sure to replace [Version] in the title above.  If necessary, update the testing
        platform, and provide any special instructions.  Assign to a developer for
        completion. 

  - type: textarea
    id: instructions
    attributes:
      label: Instructions
      value: >-
        Please test the release candidate running on the platform noted below and confirm
        the assertions listed below; check the box by each assertion when you have
        confirmed compliance.  If you encounter problems, describe them in comments to
        this issue (and @-tag relevent devlopers), and consider creating a sub-issue.
        When all assertions are confirmed and no problems remain open, click the "Testing
        Complete" box and close this issue.


        Note checking multiple broswers or OS platforms is _not_ required, unless explicitly
        requested.


        See the [Acceptance Testing page on
        Confluence](https://nistgov.atlassian.net/wiki/spaces/OKB/pages/15959145/Acceptance+Testing)
        for more information.  

  - type: input
    id: platform
    attributes:
      label: Testing Platform
      value: testdata.nist.gov
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Science Data Portal (SDP)"

  - type: checkboxes
    id: sdp_checks
    attributes:
      label: SDP Checklist
      options:
        - label: Recent publications are displaying (indicating successful access to the RMM)
        - label: Can access curated collection pages from SDP
        - label: Topic area searches complete
        - label: Default no-text search from SDP home page completes
        - label: Can complete free text search from SDP home page, suggestions pop up properly
        - label: API page has working link to RMM API
        - label: Page size responds well to resizing, phone display size
        - label: CTS logo displays
        - label: Ensure Release version badge is up to date

  - type: markdown
    attributes:
      value: "## Search Results"

  - type: checkboxes
    id: search_checks
    attributes:
      label: Search Results Checklist
      options:
        - label: suggestion completion is working, and displays properly
        - label: Filters (particularly research areas) display properly (and in a timely manner)
        - label: Suggestion completion on Author and Keyword filters work and display properly
        - label: Research topics include numbers of hits
        - label: Clicking on topics successfully down-select results

  - type: checkboxes
    id: browser
    attributes:
      label: Browser(s) tested on (check all that apply; all not required)
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge
        - label: Other
          
  - type: checkboxes
    id: os
    attributes:
      label: OS platform(s) tested on (check all that apply; all not required)
      options:
        - label: Mac
        - label: Linux
        - label: Windows
        - label: Android
        - label: iOS (IPhone/IPad)
        - label: Other
          
  - type: checkboxes
    id: completion
    attributes:
      label: Testing Completed
      options:
        - label: all acceptance tests completed with no issues found


